---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: false
  fixme:
    enabled: false
  phpmd:
    enabled: false
  radon:
    enabled: false
  gofmt:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.go"
exclude_paths: []
